# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 181d0ff41e579e5efeb55cfea684539ea633fa60a4d6cc8953ef57e4064fbf754094fcfd6882d6e76544f41af77b75cf70bb7b580fe2ff74c72a0aa0ca85aed8

test:
  secret_key_base: 42d1b2b8dbe0f439cbca7e77963d7bfd5977784bd19d84e2736526814fe3b163ee30780bf8677a2e5a66399ac69e19862c74399e5df76c256525cf331301beda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
